name = "Microgrids"
uuid = "bd581358-d3fa-499e-a26e-e70307242c03"
authors = ["Pierre Haessig <pierre.haessig@centralesupelec.fr>", "evelisea <59697806+evelisea@users.noreply.github.com>","Jean NIKIEMA <jean.nikiema@centralesupelec.fr.com>"]
version = "0.10.5"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"

[compat]
julia = "1.6"
